backend:
  name: github
  repo: gerona-ina/ina-portfolio
  branch: main
  base_url: https://arkiv-ina.net
  auth_endpoint: .netlify/functions/oauth-start

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "writing"
    label: "Writing"
    folder: "writing/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "projects/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }